services:
  backend:
    build:
      context: ./IGI_API
    container_name: igi_api
    ports:
      - "8080:8080"
    environment:
      - BASE_URL=http://localhost:8080
      - SWAPI_BASE_URL=https://www.swapi.tech/api/
      - SWAGGER_URL=http://localhost:8080/docs/
    networks:
      - igi_network

  frontend:
    build:
      context: ./IGI_CLIENT
    container_name: igi_client
    volumes:
      - ./IGI_CLIENT/dist:/usr/share/nginx/html
    ports:
      - "3000:80"
    environment:
      - IGI_API_DEV=http://backend:8080
    depends_on:
      - backend
    networks:
      - igi_network

  # proxy server to PORT 6969 for Nginx (frontend and backend)
  proxy:
    image: nginx:alpine
    container_name: igi_proxy
    volumes: # mount the files to the container
      - ./IGI_CLIENT/dist:/usr/share/nginx/html # frontend
      - ./nginx.conf:/etc/nginx/nginx.conf # nginx configuration
    ports:
      - "6969:80"
    depends_on:
      - backend
      - frontend
    networks:
      - igi_network

networks:
  igi_network:
    driver: bridge
